#!/usr/bin/env bash

# The base dir of the check
base_dir=$1
# The exit code for the check. By default, 0 is set to indicate a successful check
exit_code=0

# unsecuredPaths :: String -> IO String
unsecuredPaths() {
  local base_dir=$(readlink -f "$1")
  local usp="$(find "$base_dir" -perm 777 -type d -prune | /usr/bin/unsecured_paths)"

  if [[ -n "$usp" ]]; then
    echo "$usp"
    return 1
  fi
}

# main function
main=$(unsecuredPaths $base_dir)
main_ret=$?

if [[ $main_ret -ne 0 ]]; then
  echo "Found writable directories|"
  echo "$main"
  exit $main_ret
else
  echo "OK"
fi
